### ISSUE TITLE
Problem running in Ubuntu

### ISSUE THREAD

**Issue by interpretivechaos** [klusta-team/example#3]
I'm trying to get klustakwik/klustasuite working on my Ubuntu machine. Running klusta params.prm in the sample data causes the following error. I'd be happy to debug it: does anyone else have problems running it as instructed in linux, or another route for installing I should try?

Thanks!

```
~/Downloads/example-master$ klusta params.prm --overwrite
2015-03-24 15:36:58  __dir__ needs to be an attribute of /
2015-03-24 15:36:58  __members__ needs to be an attribute of /
2015-03-24 15:36:58  __methods__ needs to be an attribute of /
2015-03-24 15:36:58  __dir__ needs to be an attribute of 0
2015-03-24 15:36:58  __members__ needs to be an attribute of 0
2015-03-24 15:36:58  __methods__ needs to be an attribute of 0
2015-03-24 15:36:58  __dir__ needs to be an attribute of 0
2015-03-24 15:36:58  __members__ needs to be an attribute of 0
2015-03-24 15:36:58  __methods__ needs to be an attribute of 0
2015-03-24 15:36:58  __dir__ needs to be an attribute of cluster_groups
2015-03-24 15:36:58  __members__ needs to be an attribute of cluster_groups
2015-03-24 15:36:58  __methods__ needs to be an attribute of cluster_groups
2015-03-24 15:36:58  __dir__ needs to be an attribute of main
2015-03-24 15:36:58  __members__ needs to be an attribute of main
2015-03-24 15:36:58  __methods__ needs to be an attribute of main
2015-03-24 15:36:58  __dir__ needs to be an attribute of original
2015-03-24 15:36:58  __members__ needs to be an attribute of original
2015-03-24 15:36:58  __methods__ needs to be an attribute of original
2015-03-24 15:36:58  __dir__ needs to be an attribute of clusters
2015-03-24 15:36:58  __members__ needs to be an attribute of clusters
2015-03-24 15:36:58  __methods__ needs to be an attribute of clusters
2015-03-24 15:36:58  __dir__ needs to be an attribute of main
2015-03-24 15:36:58  __members__ needs to be an attribute of main
2015-03-24 15:36:58  __methods__ needs to be an attribute of main
2015-03-24 15:36:58  __dir__ needs to be an attribute of original
2015-03-24 15:36:58  __members__ needs to be an attribute of original
2015-03-24 15:36:58  __methods__ needs to be an attribute of original
2015-03-24 15:36:58  __dir__ needs to be an attribute of spikes
2015-03-24 15:36:58  __members__ needs to be an attribute of spikes
2015-03-24 15:36:58  __methods__ needs to be an attribute of spikes
2015-03-24 15:36:58  __dir__ needs to be an attribute of clusters
2015-03-24 15:36:58  __members__ needs to be an attribute of clusters
2015-03-24 15:36:58  __methods__ needs to be an attribute of clusters
2015-03-24 15:36:58  __dir__ needs to be an attribute of 0
2015-03-24 15:36:58  __members__ needs to be an attribute of 0
2015-03-24 15:36:58  __methods__ needs to be an attribute of 0
2015-03-24 15:36:58  Starting process on <ExperimentRawReader <Experiment 'test_hybrid_120sec'>
    application_data
        spikedetekt
            canonical_pcs = None
            chunk_overlap = 300
            chunk_size = 20000
            connected_component_join_size = 1
            detect_spikes = negative
            diagnostics_script_path = None
            excerpt_size = 20000
            experiment_name = test_hybrid_120sec
            extract_s_after = 10
            extract_s_before = 10
            features_contiguous
            filter_butter_order = 3
            filter_high = 9500.0
            filter_low = 500.0
            nbits = 16
            nchannels = 32
            nexcerpts = 50
            nfeatures_per_channel = 3
            pca_nwaveforms_max = 10000
            prb_file = 32chan1shankbuzsaki.prb
            raw_data_files = test_hybrid_120sec.raw.kwd
            sample_rate = 20000
            save_high
            save_low
            save_raw
            threshold_strong_std_factor = 4.5
            threshold_weak_std_factor = 2.0
            use_single_threshold
            voltage_gain = 10.0
            waveforms_nsamples = 20
            weight_power = 2
    channel_groups
        0
            application_data
            channels
                0
                    application_data
                        klustaviewa
                        spikedetekt
                    user_data
            cluster_groups
                main
                    add_group
                    color
                    iteritems
                    keys
                    name
                    remove_group
                    values
                original
                    add_group
                    color
                    iteritems
                    keys
                    name
                    remove_group
                    values
            clusters
                main
                    add_cluster
                    color
                    group
                    iteritems
                    keys
                    remove_cluster
                    values
                original
                    add_cluster
                    color
                    group
                    iteritems
                    keys
                    remove_cluster
                    values
            spikes
                add
                channel_group_id = 0
                clusters
                    copy
                    main [uint32 (0,)]
                    original [uint32 (0,)]
                concatenated_time_samples
                features
                    dtype
                features_masks [float32 (0, 96, 2)]
                init_cache
                load_features_masks
                load_features_masks_bg
                load_waveforms
                masks
                    dtype
                nchannels = 32
                nfeatures = 96
                nsamples = 20
                recording [uint16 (0,)]
                time_fractional [uint8 (0,)]
                time_samples [uint64 (0,)]
                waveforms_filtered [int16 (0, 20, 32)]
                waveforms_raw [int16 (0, 20, 32)]
            user_data
    close
    dir = 
    gen_filename
    name = test_hybrid_120sec
    recordings
        0
            high [int16 (0, 32)]
            low [int16 (0, 32)]
            raw [int16 (0, 32)]
            user_data
    user_data>
2015-03-24 15:36:58  Traceback (most recent call last):
  File "/home/me/Programming/miniconda/envs/klusta/bin/klusta", line 9, in <module>
    load_entry_point('klustaviewa==0.3.0rc1', 'console_scripts', 'klusta')()
  File "/home/me/Programming/miniconda/envs/klusta/lib/python2.7/site-packages/klustaviewa-0.3.0rc1-py2.7-linux-x86_64.egg/spikedetekt2/core/script.py", line 267, in main
    runsd=runsd, runkk=runkk)
  File "/home/me/Programming/miniconda/envs/klusta/lib/python2.7/site-packages/klustaviewa-0.3.0rc1-py2.7-linux-x86_64.egg/spikedetekt2/core/script.py", line 237, in run_all
    run_spikedetekt(prm_filename, dir=dir, debug=debug)
  File "/home/me/Programming/miniconda/envs/klusta/lib/python2.7/site-packages/klustaviewa-0.3.0rc1-py2.7-linux-x86_64.egg/spikedetekt2/core/script.py", line 115, in run_spikedetekt
    _debug=debug)
  File "/home/me/Programming/miniconda/envs/klusta/lib/python2.7/site-packages/klustaviewa-0.3.0rc1-py2.7-linux-x86_64.egg/spikedetekt2/core/main.py", line 182, in run
    channels=probe.channels, **prm)
  File "/home/me/Programming/miniconda/envs/klusta/lib/python2.7/site-packages/klustaviewa-0.3.0rc1-py2.7-linux-x86_64.egg/spikedetekt2/processing/threshold.py", line 46, in get_threshold
    excerpt_size=excerpt_size))
  File "/home/me/Programming/miniconda/envs/klusta/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
None
```

**Comment by NikiGuo** [comment]
I think you have downloaded the empty data file; try downloading the data from Example data repository

**Comment by grg2rsr** [comment]
I got klusta to run using [this](https://github.com/klusta-team/example/blob/master/params.prm), parameter file, not with the one that ships out with the .zip. Seems to run fine, but I can't open the resulting .kwik file klustaviewa. Posting an issue there as well ...
